import {
  HeartPulse,
  Brain,
  Bone,
  Baby,
  Ribbon,
  Sparkles,
  ClipboardCheck,
  Microscope,
  Ambulance,
  Stethoscope,
  Pill,
  Video,
  Activity,
  Receipt,
  ClipboardList,
  ShieldCheck,
  FileCheck,
  RefreshCw,
  Wallet,
  BadgeCheck,
  BarChart3,
  LayoutGrid,
  Calendar,
  Info,
  Phone,
  Hospital,
  Cross,
  HeartHandshake,
  Syringe,
  MapPin,
  HelpCircle,
  type LucideIcon,
} from "lucide-react";

/** Curated registry so data can reference icons by name (string) safely. */
const registry: Record<string, LucideIcon> = {
  HeartPulse,
  Brain,
  Bone,
  Baby,
  Ribbon,
  Sparkles,
  ClipboardCheck,
  Microscope,
  Ambulance,
  Stethoscope,
  Pill,
  Video,
  Receipt,
  ClipboardList,
  ShieldCheck,
  FileCheck,
  RefreshCw,
  Wallet,
  BadgeCheck,
  BarChart3,
  LayoutGrid,
  Calendar,
  Info,
  Phone,
  Hospital,
  Cross,
  HeartHandshake,
  Syringe,
  MapPin,
  HelpCircle,
};

export function Icon({ name, className }: { name: string; className?: string }) {
  const Cmp = registry[name] ?? Activity;
  return <Cmp className={className} aria-hidden />;
}
